name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app
    
      - name: Build and test
        run: xcodebuild clean build test -project EssentialFeed -scheme CI
